services:
  app:
    build: .
    ports:
      - "3005:80"
    env_file: .env
    networks:
      - shared_db
    command: sh -c "bundle exec rails db:prepare && (bundle exec rails rswag:specs:swaggerize || true) && ./bin/thrust ./bin/rails server"

networks:
  shared_db:
    external: true
