---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users/sign_in":
    post:
      summary: Sign in
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: user signed in
        '401':
          description: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
